export enum Path {
  CONNECT_TO_REMOTE = "/connect_remote",
  CONNECTION_LOST = "/connection_lost",
  DASHBOARD = "/dashboard",
  DOWNLOAD_DOCKER = "/download_docker",
  HOME = "/",
  INSTALL_DOCKER = "/install_docker",
  RESTART_REQUIRED = "/restart_required",
  START_ENVIRONMENT = "/start_environment",
  STARTING_OPENDEX = "/starting_opendex",
  WAITING_DOCKER_START = "/waiting_docker_start",
  INCOMPATIBLE_WSL_SETTINGS = "/incompatible_wsl_settings",
  INSTALL_DOCKER_COMPOSE = "/install-docker-compose",
  DOCKER_PERMISSION_DENIED = "/docker-permission-denied",
}
